import type { ChainDefinition } from '@/types'
import { BRAND } from './brand'

const NOVAONE_COLOR = BRAND.chainColors.novaone
const NRW_COLOR = BRAND.chainColors.nrw

/** Canonical chain registry — mesh, partner, NovaONE / NRW World, top public EVMs */
export const CHAINS: ChainDefinition[] = [
  {
    id: 11011,
    name: 'AnakaChain',
    slug: 'anakachain',
    nativeCurrency: { name: 'Anaka Gas', symbol: 'AGAS', decimals: 18 },
    rpcUrls: ['https://rpc.anakachain.com'],
    blockExplorerUrls: ['https://explorer.anakachain.com'],
    iconColor: BRAND.chainColors.anakachain,
    category: 'anaka',
    tier: 'public',
    isDefault: true,
    isInternal: false,
    tokens: [{ symbol: 'AGAS', name: 'Anaka Gas', decimals: 18, address: null, standard: 'native' }],
  },
  {
    id: 22016,
    name: 'NovaOne',
    slug: 'novaone',
    nativeCurrency: { name: 'Nova Token', symbol: 'NOVA', decimals: 18 },
    rpcUrls: [
      'https://anakatech.llc/novaone-rpc/',
      'https://novaone-rpc.anakatech.llc',
    ],
    blockExplorerUrls: ['https://novaone.anakatech.llc'],
    iconColor: NOVAONE_COLOR,
    category: 'anaka',
    tier: 'private-banking',
    isDefault: true,
    isInternal: false,
    zeroGas: true,
    tokens: [
      { symbol: 'NOVA', name: 'Nova Token', decimals: 18, address: null, standard: 'native' },
      {
        symbol: 'AnA',
        name: 'Anaka',
        decimals: 18,
        address: '0xc05F5B8A193bECA1744E42D4c3c516DBC49f7d8B',
        standard: 'erc20',
        usd: 1,
      },
      {
        symbol: 'WAGAS',
        name: 'Wrapped AGAS',
        decimals: 18,
        address: '0x01396c382FeCb30548FFa3f9D9da2252C3C94748',
        standard: 'erc20',
        usd: 0.01,
      },
    ],
  },
  {
    id: 33001,
    name: 'NRW World Chain',
    slug: 'nrw',
    nativeCurrency: { name: 'NRW', symbol: 'NRW', decimals: 18 },
    rpcUrls: ['https://nrw-world-chain-production-6029.up.railway.app'],
    blockExplorerUrls: ['https://nrw.anakatech.llc'],
    iconColor: NRW_COLOR,
    category: 'partner',
    tier: 'partner',
    isDefault: true,
    isInternal: false,
    tokens: [{ symbol: 'NRW', name: 'NRW', decimals: 18, address: null, standard: 'native' }],
  },
  {
    id: 138,
    name: 'Defi Oracle Meta',
    slug: 'defi-oracle',
    nativeCurrency: { name: 'Defi Oracle', symbol: 'DFO', decimals: 18 },
    rpcUrls: ['https://rpc.public-0138.defi-oracle.io', 'https://rpc.defi-oracle.io'],
    blockExplorerUrls: ['https://explorer.d-bis.org'],
    iconColor: BRAND.chainColors.defiOracle,
    category: 'partner',
    tier: 'partner',
    isDefault: true,
    isInternal: false,
    bridge: { address: '0x8445976FE32257Eb03B1F02e8A11Fd2c0041ce8c' },
    tokens: [
      { symbol: 'DFO', name: 'Defi Oracle', decimals: 18, address: null, standard: 'native' },
      {
        symbol: 'USDT',
        name: 'Tether USD',
        decimals: 6,
        address: '0x004b63A7B7eF5F5E8e7e7e7e7e7e7e7e7e7e7e7e',
        standard: 'erc20',
        usd: 1,
        coingeckoId: 'tether',
      },
    ],
  },
  {
    id: 651940,
    name: 'ALLTRA',
    slug: 'alltra',
    nativeCurrency: { name: 'ALLTRA', symbol: 'ALL', decimals: 18 },
    rpcUrls: ['https://mainnet-rpc.alltra.global'],
    blockExplorerUrls: ['https://alltra.global'],
    iconColor: BRAND.chainColors.alltra,
    category: 'partner',
    tier: 'partner',
    isDefault: true,
    isInternal: false,
    tokens: [{ symbol: 'ALL', name: 'ALLTRA', decimals: 18, address: null, standard: 'native' }],
  },
  {
    id: 1,
    name: 'Ethereum',
    slug: 'ethereum',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: ['https://ethereum-rpc.publicnode.com', 'https://cloudflare-eth.com'],
    blockExplorerUrls: ['https://etherscan.io'],
    iconColor: '#627EEA',
    category: 'public',
    tier: 'public',
    isDefault: true,
    isInternal: false,
    tokens: [
      { symbol: 'ETH', name: 'Ether', decimals: 18, address: null, standard: 'native', coingeckoId: 'ethereum' },
      {
        symbol: 'USDC',
        name: 'USD Coin',
        decimals: 6,
        address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
        standard: 'erc20',
        usd: 1,
        coingeckoId: 'usd-coin',
      },
      {
        symbol: 'USDT',
        name: 'Tether USD',
        decimals: 6,
        address: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
        standard: 'erc20',
        usd: 1,
        coingeckoId: 'tether',
      },
    ],
  },
  {
    id: 56,
    name: 'BNB Chain',
    slug: 'bnb',
    nativeCurrency: { name: 'BNB', symbol: 'BNB', decimals: 18 },
    rpcUrls: ['https://bsc-dataseed.bnbchain.org'],
    blockExplorerUrls: ['https://bscscan.com'],
    iconColor: '#F0B90B',
    category: 'public',
    tier: 'public',
    isDefault: true,
    isInternal: false,
    tokens: [{ symbol: 'BNB', name: 'BNB', decimals: 18, address: null, standard: 'native', coingeckoId: 'binancecoin' }],
  },
  {
    id: 42161,
    name: 'Arbitrum One',
    slug: 'arbitrum',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: ['https://arb1.arbitrum.io/rpc'],
    blockExplorerUrls: ['https://arbiscan.io'],
    iconColor: '#28A0F0',
    category: 'public',
    tier: 'public',
    isDefault: true,
    isInternal: false,
    tokens: [{ symbol: 'ETH', name: 'Ether', decimals: 18, address: null, standard: 'native', coingeckoId: 'ethereum' }],
  },
  {
    id: 8453,
    name: 'Base',
    slug: 'base',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: ['https://mainnet.base.org'],
    blockExplorerUrls: ['https://basescan.org'],
    iconColor: '#0052FF',
    category: 'public',
    tier: 'public',
    isDefault: true,
    isInternal: false,
    tokens: [{ symbol: 'ETH', name: 'Ether', decimals: 18, address: null, standard: 'native', coingeckoId: 'ethereum' }],
  },
  {
    id: 137,
    name: 'Polygon',
    slug: 'polygon',
    nativeCurrency: { name: 'POL', symbol: 'POL', decimals: 18 },
    rpcUrls: ['https://polygon-bor-rpc.publicnode.com'],
    blockExplorerUrls: ['https://polygonscan.com'],
    iconColor: '#8247E5',
    category: 'public',
    tier: 'public',
    isDefault: true,
    isInternal: false,
    tokens: [{ symbol: 'POL', name: 'POL', decimals: 18, address: null, standard: 'native', coingeckoId: 'matic-network' }],
  },
  {
    id: 10,
    name: 'Optimism',
    slug: 'optimism',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: ['https://mainnet.optimism.io'],
    blockExplorerUrls: ['https://optimistic.etherscan.io'],
    iconColor: '#FF0420',
    category: 'public',
    tier: 'public',
    isDefault: true,
    isInternal: false,
    tokens: [{ symbol: 'ETH', name: 'Ether', decimals: 18, address: null, standard: 'native', coingeckoId: 'ethereum' }],
  },
  {
    id: 43114,
    name: 'Avalanche',
    slug: 'avalanche',
    nativeCurrency: { name: 'AVAX', symbol: 'AVAX', decimals: 18 },
    rpcUrls: ['https://api.avax.network/ext/bc/C/rpc'],
    blockExplorerUrls: ['https://snowtrace.io'],
    iconColor: '#E84142',
    category: 'public',
    tier: 'public',
    isDefault: false,
    isInternal: false,
    tokens: [{ symbol: 'AVAX', name: 'AVAX', decimals: 18, address: null, standard: 'native', coingeckoId: 'avalanche-2' }],
  },
  {
    id: 100,
    name: 'Gnosis',
    slug: 'gnosis',
    nativeCurrency: { name: 'xDAI', symbol: 'xDAI', decimals: 18 },
    rpcUrls: ['https://rpc.gnosischain.com'],
    blockExplorerUrls: ['https://gnosisscan.io'],
    iconColor: '#3E6957',
    category: 'public',
    tier: 'public',
    isDefault: false,
    isInternal: false,
    tokens: [{ symbol: 'xDAI', name: 'xDAI', decimals: 18, address: null, standard: 'native', usd: 1 }],
  },
  {
    id: 324,
    name: 'zkSync Era',
    slug: 'zksync',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: ['https://mainnet.era.zksync.io'],
    blockExplorerUrls: ['https://explorer.zksync.io'],
    iconColor: '#8B5CF6',
    category: 'public',
    tier: 'public',
    isDefault: false,
    isInternal: false,
    tokens: [{ symbol: 'ETH', name: 'Ether', decimals: 18, address: null, standard: 'native', coingeckoId: 'ethereum' }],
  },
  {
    id: 59144,
    name: 'Linea',
    slug: 'linea',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: ['https://rpc.linea.build'],
    blockExplorerUrls: ['https://lineascan.build'],
    iconColor: '#62688F',
    category: 'public',
    tier: 'public',
    isDefault: false,
    isInternal: false,
    tokens: [{ symbol: 'ETH', name: 'Ether', decimals: 18, address: null, standard: 'native', coingeckoId: 'ethereum' }],
  },
  {
    id: 534352,
    name: 'Scroll',
    slug: 'scroll',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: ['https://rpc.scroll.io'],
    blockExplorerUrls: ['https://scrollscan.com'],
    iconColor: '#FF684B',
    category: 'public',
    tier: 'public',
    isDefault: false,
    isInternal: false,
    tokens: [{ symbol: 'ETH', name: 'Ether', decimals: 18, address: null, standard: 'native', coingeckoId: 'ethereum' }],
  },
  {
    id: 5000,
    name: 'Mantle',
    slug: 'mantle',
    nativeCurrency: { name: 'MNT', symbol: 'MNT', decimals: 18 },
    rpcUrls: ['https://rpc.mantle.xyz'],
    blockExplorerUrls: ['https://mantlescan.xyz'],
    iconColor: '#65B3AE',
    category: 'public',
    tier: 'public',
    isDefault: false,
    isInternal: false,
    tokens: [{ symbol: 'MNT', name: 'Mantle', decimals: 18, address: null, standard: 'native', coingeckoId: 'mantle' }],
  },
  {
    id: 81457,
    name: 'Blast',
    slug: 'blast',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: ['https://rpc.blast.io'],
    blockExplorerUrls: ['https://blastscan.io'],
    iconColor: '#FCFC03',
    category: 'public',
    tier: 'public',
    isDefault: false,
    isInternal: false,
    tokens: [{ symbol: 'ETH', name: 'Ether', decimals: 18, address: null, standard: 'native', coingeckoId: 'ethereum' }],
  },
  {
    id: 42220,
    name: 'Celo',
    slug: 'celo',
    nativeCurrency: { name: 'CELO', symbol: 'CELO', decimals: 18 },
    rpcUrls: ['https://forno.celo.org'],
    blockExplorerUrls: ['https://celoscan.io'],
    iconColor: '#FCFF52',
    category: 'public',
    tier: 'public',
    isDefault: false,
    isInternal: false,
    tokens: [{ symbol: 'CELO', name: 'Celo', decimals: 18, address: null, standard: 'native', coingeckoId: 'celo' }],
  },
  {
    id: 25,
    name: 'Cronos',
    slug: 'cronos',
    nativeCurrency: { name: 'CRO', symbol: 'CRO', decimals: 18 },
    rpcUrls: ['https://evm.cronos.org'],
    blockExplorerUrls: ['https://cronoscan.com'],
    iconColor: '#1199FA',
    category: 'public',
    tier: 'public',
    isDefault: false,
    isInternal: false,
    tokens: [{ symbol: 'CRO', name: 'Cronos', decimals: 18, address: null, standard: 'native', coingeckoId: 'crypto-com-chain' }],
  },
  {
    id: 11012,
    name: 'AnakaChain Tokenisation',
    slug: 'anaka-tokenisation',
    nativeCurrency: { name: 'Anaka Gas', symbol: 'AGAS', decimals: 18 },
    rpcUrls: ['https://assets.anakachain.com'],
    blockExplorerUrls: ['https://anakachain.com'],
    iconColor: BRAND.chainColors.anakachain,
    category: 'anaka',
    tier: 'private-banking',
    isDefault: false,
    isInternal: true,
    tokens: [{ symbol: 'AGAS', name: 'Anaka Gas', decimals: 18, address: null, standard: 'native' }],
  },
  {
    id: 11013,
    name: 'AnakaChain Bridge',
    slug: 'anaka-bridge',
    nativeCurrency: { name: 'Anaka Gas', symbol: 'AGAS', decimals: 18 },
    rpcUrls: ['https://bridge.anakachain.com'],
    blockExplorerUrls: ['https://anakachain.com'],
    iconColor: BRAND.chainColors.anakachain,
    category: 'anaka',
    tier: 'private-banking',
    isDefault: false,
    isInternal: true,
    tokens: [{ symbol: 'AGAS', name: 'Anaka Gas', decimals: 18, address: null, standard: 'native' }],
  },
  {
    id: 11014,
    name: 'AnakaChain Sovereign',
    slug: 'anaka-sovereign',
    nativeCurrency: { name: 'Anaka Gas', symbol: 'AGAS', decimals: 18 },
    rpcUrls: ['https://sovereign.anakachain.com'],
    blockExplorerUrls: ['https://anakachain.com'],
    iconColor: BRAND.chainColors.anakachain,
    category: 'anaka',
    tier: 'private-banking',
    isDefault: false,
    isInternal: true,
    tokens: [{ symbol: 'AGAS', name: 'Anaka Gas', decimals: 18, address: null, standard: 'native' }],
  },
  {
    id: 11015,
    name: 'AnakaChain Enclave',
    slug: 'anaka-enclave',
    nativeCurrency: { name: 'Anaka Gas', symbol: 'AGAS', decimals: 18 },
    rpcUrls: ['https://enclave.anakachain.com'],
    blockExplorerUrls: ['https://anakachain.com'],
    iconColor: BRAND.chainColors.anakachain,
    category: 'anaka',
    tier: 'private-banking',
    isDefault: false,
    isInternal: true,
    tokens: [{ symbol: 'AGAS', name: 'Anaka Gas', decimals: 18, address: null, standard: 'native' }],
  },
]

export function getChain(id: number): ChainDefinition | undefined {
  return CHAINS.find((c) => c.id === id)
}

export function getChainBySlug(slug: string): ChainDefinition | undefined {
  return CHAINS.find((c) => c.slug === slug)
}

export function defaultChainIds(): number[] {
  return CHAINS.filter((c) => c.isDefault).map((c) => c.id)
}

export function publicEvmChains(): ChainDefinition[] {
  return CHAINS.filter((c) => c.category === 'public')
}

export function partnerChains(): ChainDefinition[] {
  return CHAINS.filter((c) => c.category === 'partner')
}

export function anakaMeshChains(): ChainDefinition[] {
  return CHAINS.filter((c) => c.category === 'anaka')
}

export function privateBankingChains(): ChainDefinition[] {
  return CHAINS.filter((c) => c.tier === 'private-banking')
}

export function explorerTxUrl(chainId: number, hash: string): string | null {
  const chain = getChain(chainId)
  if (!chain?.blockExplorerUrls[0]) return null
  return `${chain.blockExplorerUrls[0].replace(/\/$/, '')}/tx/${hash}`
}

export function chainBadgeStyle(chainId: number): { background: string; color: string } {
  const chain = getChain(chainId)
  const bg = chain?.iconColor ?? BRAND.colors.gold
  return { background: bg, color: '#0d0606' }
}
