export const ROUTES = {
  home: '/',
  onboarding: '/onboarding',
  import: '/import',
  unlock: '/unlock',
  portfolio: '/portfolio',
  dashboard: '/portfolio',
  assets: '/assets',
  tokens: '/tokens',
  tokenChart: '/tokens/:symbol/chart',
  send: '/send',
  receive: '/receive',
  swap: '/swap',
  bridge: '/bridge',
  banks: '/banks',
  more: '/more',
  activity: '/activity',
  settings: '/settings',
  settingsAccounts: '/settings/accounts',
  settingsGeneral: '/settings/general',
  settingsSecurity: '/settings/security',
  settingsBackup: '/settings/backup',
  settingsNetwork: '/settings/network',
  settingsDisplay: '/settings/display',
  settingsNotifications: '/settings/notifications',
  settingsConnections: '/settings/connections',
  settingsAdvanced: '/settings/advanced',
  settingsFafo: '/settings/fafo',
  settingsAbout: '/settings/about',
  accounts: '/accounts',
  networks: '/networks',
  multisig: '/multisig',
  multisigCreate: '/multisig/create',
  multisigPending: '/multisig/pending',
  walletConnect: '/wallet-connect',
  insights: '/insights',
  institutional: '/institutional',
} as const

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES]
