/** Generated from branding/brand-tokens.json */
export const BRAND = {
  name: 'Nova Wallet',
  shortName: 'Nova',
  bundleId: 'llc.anakatech.novawallet',
  domain: 'anakatech.llc',
  organization: 'Anakatech',
  headline: 'Trade the mesh.',
  colors: {
    bg: '#000000',
    bgAlt: '#0A0A0A',
    surface: '#121212',
    surfaceRaised: '#1A1A1A',
    accent: '#14B8A6',
    highlight: '#2DD4BF',
    ink: '#FFFFFF',
    muted: '#8B8B8B',
    border: 'rgba(255,255,255,0.08)',
    danger: '#F6465D',
    success: '#0ECB81',
  },
  chainColors: {
    novaone: '#0EA5E9',
    nrw: '#14B8A6',
    novaProduction: '#38BDF8',
    novaPlus: '#38BDF8',
    defiOracle: '#2DD4BF',
    anaka: '#F59E0B',
    alltra: '#E8D48B',
  },
} as const
