import type { WalletOption } from './types'

/** Curated Web3 wallets — MetaMask, Trust, SafePal, Gate, and common injected wallets */
export const WALLET_CATALOG: WalletOption[] = [
  {
    id: 'metamask',
    name: 'MetaMask',
    subtitle: 'Browser extension & mobile',
    accent: '#F6851B',
    rdns: ['io.metamask', 'io.metamask.mobile'],
    flags: (p) => !!p.isMetaMask && !p.isRabby && !p.isBraveWallet,
    installUrl: 'https://metamask.io/download/',
    deepLink: (url) => `https://metamask.app.link/dapp/${url.replace(/^https?:\/\//, '')}`,
  },
  {
    id: 'trust',
    name: 'Trust Wallet',
    subtitle: 'Mobile & browser',
    accent: '#0500FF',
    rdns: ['com.trustwallet.app'],
    flags: (p) => !!(p.isTrust || p.isTrustWallet),
    installUrl: 'https://trustwallet.com/download',
    deepLink: (url) =>
      `https://link.trustwallet.com/open_url?coin_id=60&url=${encodeURIComponent(url)}`,
  },
  {
    id: 'safepal',
    name: 'SafePal',
    subtitle: 'Hardware & software wallet',
    accent: '#4A21EF',
    rdns: ['com.safepal', 'io.safepal'],
    flags: (p) => !!p.isSafePal,
    installUrl: 'https://www.safepal.com/download',
  },
  {
    id: 'gate',
    name: 'Gate Wallet',
    subtitle: 'Gate.io Web3 wallet',
    accent: '#17E6A1',
    rdns: ['io.gateio', 'com.gate.wallet', 'io.gatewallet'],
    flags: (p) => !!p.isGateWallet,
    installUrl: 'https://www.gate.io/web3',
  },
  {
    id: 'okx',
    name: 'OKX Wallet',
    subtitle: 'OKX Web3',
    accent: '#000000',
    rdns: ['com.okex.wallet'],
    installUrl: 'https://www.okx.com/web3',
  },
  {
    id: 'coinbase',
    name: 'Coinbase Wallet',
    subtitle: 'Extension & mobile',
    accent: '#0052FF',
    rdns: ['com.coinbase.wallet'],
    flags: (p) => !!p.isCoinbaseWallet,
    installUrl: 'https://www.coinbase.com/wallet/downloads',
  },
  {
    id: 'rabby',
    name: 'Rabby',
    subtitle: 'Multi-chain DeFi wallet',
    accent: '#7084FF',
    rdns: ['io.rabby'],
    flags: (p) => !!p.isRabby,
    installUrl: 'https://rabby.io/',
  },
  {
    id: 'brave',
    name: 'Brave Wallet',
    subtitle: 'Built into Brave browser',
    accent: '#FB542B',
    rdns: ['com.brave.wallet'],
    flags: (p) => !!p.isBraveWallet,
    installUrl: 'https://brave.com/wallet/',
  },
  {
    id: 'bitget',
    name: 'Bitget Wallet',
    subtitle: 'Formerly BitKeep',
    accent: '#00F0FF',
    rdns: ['com.bitget.web3', 'com.bitkeep.wallet'],
    installUrl: 'https://web3.bitget.com/en/wallet',
  },
  {
    id: 'injected',
    name: 'Browser wallet',
    subtitle: 'Any injected EIP-1193 wallet',
    accent: '#14B8A6',
  },
  {
    id: 'walletconnect',
    name: 'WalletConnect',
    subtitle: 'Use MetaMask / Trust / SafePal / Gate (injected) in production',
    accent: '#3B99FC',
    installUrl: 'https://walletconnect.com/',
  },
]
